### ISSUE TITLE
HTTP::Tiny::Handle has great read/write methods why not expose documetation

### ISSUE THREAD

**Issue by mrdvt92** [chansen/p5-http-tiny#100]
HTTP::Tiny::Handle has great read/write methods but they are not exposed in the documentation.  I'd love to use them but since they are not documented and the version is well below 1.00 I assume that the API is not stable.  

I would like for the API to be documented and exposed so that I can use HTTP::Tiny::Handle in my custom non-HTTP but TCP/IP protocol project without the fear of upgrade breakage.

**Comment by xdg** [comment]
I would recommend just copying them out and giving credit back.  We don't intend to make them a general-purpose library or support them explicitly for other purposes.  You might also want to look at how I already did that for the MongoDB Perl driver:  https://github.com/mongodb/mongo-perl-driver/blob/master/lib/MongoDB/_Link.pm

There's some MongoDB cruft there, but it gets rid of all the HTTP-isms and just has a good read/write routine.
