### ISSUE TITLE
Can't proxy https over https question

### ISSUE THREAD

**Issue by kubrat** [chansen/p5-http-tiny#101]
This is not really an issue. I am just curious to what might have been the motivation behind this error condition:

```
        if ( $proxy_vars[0] eq 'https' ) {
            _croak(qq{Can't proxy https over https: $request->{uri} via $self->{https_proxy}});
        }
```

It's probably just me but I don't see why that shouldn't be possible.

Thanks

**Comment by xdg** [comment]
It's a function of how the [CONNECT](https://tools.ietf.org/html/rfc7231#section-4.3.6) method operates.  CONNECT creates a packet tunnel from the proxy to the destination host (possibly through more proxies).  The TLS connection is made to the destination host over the tunnel.  That works by opening a non-TLS connection to the proxy, then, once CONNECT is sent and acknowledged, starting the TLS handshake.

If we allowed TLS to the proxy, there would already be an established TLS connection and you couldn't start the handshake after CONNECT.  Theoretically, one could do some fancy networking to tunnel TLS inside the TLS to the proxy, but that's not supported out-of-the box by Perl's networking stack.

TLS to the proxy doesn't add any security anyway, as the only data sent in the clear to the proxy is the target host name, which an attacker could see in DNS requests and TCP/IP headers even for making a direct TLS connection without the proxy.  Once the proxy CONNECT happens, the proxy is just a fancy packet router and the real security comes from the end-to-end TLS with the destination host (assuming certificate verification is enabled).

I hope that answers your curiosity.  :smile:

David

**Comment by kubrat** [comment]
Very clear explanation. Thanks. 

I hadn't realized that doing TLS over or within an existing TLS connection might be a problem. That probably explains why I haven't seen proxy servers that operate over TLS. 

After reading your explanation I kept thinking about it and it still feels like it should be possible. Once a CONNECT request has been granted regardless of whether you did over a TLS connection or not then you are effectively talking "direct" to the remote server.  All the client has to do at this point is start a brand new TLS handshake over the existing socket as if the existing TLS doesn't exist.

Anyway, I can't imagine this to be in high demand.

My curiosity has been satisfied. :)

Val
