### ISSUE TITLE
Accept open socket?

### ISSUE THREAD

**Issue by FGasper** [chansen/p5-http-tiny#104]
Would it be feasible to split out the HTTP logic from the actual connection logic—so that the caller could provide a pre-connect()ed socket? This would allow HTTP::Tiny to run, e.g., over a local socket.

**Comment by xdg** [comment]
Thanks for the suggestion.  We consider HTTP to feature complete and have no plans to make changes of that magnitude.  This is a "Tiny" module after all.  If local sockets are important, we suggest you use something else on CPAN.
