### ISSUE TITLE
Response hash passed to data callback missing `success` and `url` fields

### ISSUE THREAD

**Issue by bcc32** [chansen/p5-http-tiny#108]
Hi there.  I ran into a problem trying to use data callbacks with HTTP::Tiny.

Consider the following short snippet:

```perl
use HTTP::Tiny;
use Data::Dumper;

my $http = HTTP::Tiny->new;
my $url = 'https://www.google.com/humans.txt';

my $resp_wo_cb = $http->get($url);

print Dumper([sort keys %$resp_wo_cb]);

my $cb = sub {
  my ($chunk, $resp) = @_;
  print Dumper([sort keys %$resp]);
};

$http->get($url, { data_callback => $cb });
```

It produces the following output:
```
$VAR1 = [
          'content',
          'headers',
          'protocol',
          'reason',
          'status',
          'success',
          'url'
        ];
$VAR1 = [
          'content',
          'headers',
          'protocol',
          'reason',
          'status'
        ];
```

I am using HTTP::Tiny version 0.070 under Perl v5.26.1 on macOS High Sierra 10.13.3.

**Comment by xdg** [comment]
The header you get in the data callback is what exists at the time the data was received (ie things you might need for handling like content encoding headers).  Other fields are added later and you're still expected to get the return value from calling `get`.  Try this version:

```
use HTTP::Tiny;
use Data::Dumper;

my $http = HTTP::Tiny->new;
my $url = 'https://www.google.com/humans.txt';

my $resp_wo_cb = $http->get($url);

print Dumper([sort keys %$resp_wo_cb]);

my $cb = sub {
  my ($chunk, $resp) = @_;
  print Dumper([sort keys %$resp]);
};

my $resp_w_cb = $http->get($url, { data_callback => $cb });

print Dumper([sort keys %$resp_wo_cb]);
```

Result:
```
$VAR1 = [
          'content',
          'headers',
          'protocol',
          'reason',
          'status',
          'success',
          'url'
        ];
$VAR1 = [
          'content',
          'headers',
          'protocol',
          'reason',
          'status'
        ];
$VAR1 = [
          'content',
          'headers',
          'protocol',
          'reason',
          'status',
          'success',
          'url'
        ];
```

**Comment by bcc32** [comment]
Thanks for your help.  It just seems like `success` should already be available since `status` is known, and same thing for `url`.

**Comment by xdg** [comment]
`url` possibly -- but it gets added late just due to the way redirects are handled.  `success` and `status` aren't known until the network operation is complete as a network error winds up as a 599 failure.

The data callback isn't designed to pipe the whole result somewhere -- it's just to incrementally parse the body and the in-progress response is just there for reference.  If I had to do it over, I might have only provided the headers to the callback as that's all it really should need to know.

**Comment by bcc32** [comment]
Thanks for clarifying.
