### ISSUE TITLE
Status-Line reason is optional

### ISSUE THREAD

**Issue by aldot** [chansen/p5-http-tiny#119]
Status-Line without reason is incorrectly rejected.

RFC2616 specified reason-phrase a bit sloopy. This was clarified in https://tools.ietf.org/html/rfc7230#section-3.1.2
---8<---
status-line = HTTP-version SP status-code SP reason-phrase CRLF
status-code    = 3DIGIT
reason-phrase  = *( HTAB / SP / VCHAR / obs-text )
---8<---
i.e. the reason-phrase is optional. (There is still an issue in this specification for the SP before reason-phrase in status-line is optional, too, in practise, but oh well).

Unfortunately you incorrectly reject my following Status line:
---8<---
perl -le 'my $line="HTTP/1.1 200\r\n"; $line  =~ /\A (HTTP\/(0*\d+\.0*\d+)) [\x09\x20]+ ([0-9]{3}) [\x09\x20]+ ([^\x0D\x0A]*) \x0D?\x0A/x or die("Malformed Status-Line\n")'
Malformed Status-Line
---8<---

The regex should be something more along the lines of:
/\A (HTTP\/(0*\d+\.0*\d+)) [\x09\x20]+ ([0-9]{3}) (?:[\x09\x20]+ ([^\x0D\x0A]*))? \x0D?\x0A/x

**Comment by aldot** [comment]
Untested patch.
Accepts either of
"HTTP1/1 200\r\n"
"HTTP1/1 200 Foo\r\n"
But not
"HTTP1/1 200 \r\n"

I think this is in the spirit of the (still slightly broken) RFC7230.
Someone might enjoy to file an errata against 7230#3.1.2 to remove the "SP" in
'status-code SP reason-phrase' since that SP should come from reason-phrase.
I'm not going to file it, I honestly don't care enough.

Please apply.
Thanks!

[0001-Status-Line-response-phrase-is-optional.patch.txt](https://github.com/chansen/p5-http-tiny/files/3072398/0001-Status-Line-response-phrase-is-optional.patch.txt)

**Comment by aldot** [comment]
now tested

[0001-Status-Line-response-phrase-is-optional.v2.patch.txt](https://github.com/chansen/p5-http-tiny/files/3072692/0001-Status-Line-response-phrase-is-optional.v2.patch.txt)

v1 -> v2:
- allow also for odd "HTTP1/1 200 \r\n", i.e. SP after status-code but no reason-phrase
- add some tests

**Comment by aldot** [comment]
Let me note that you allow \x09 (tab) where you should only accept \x20 (space aka SP in the 7230).
I'm not changing this nor am i suggesting that it should be changed but ISTM that you're allowing more garbage in headers as the standard suggests. This is ok in practice for maximum compatibility of course.

**Comment by aldot** [comment]
> now tested
> 
> [0001-Status-Line-response-phrase-is-optional.v2.patch.txt](https://github.com/chansen/p5-http-tiny/files/3072692/0001-Status-Line-response-phrase-is-optional.v2.patch.txt)
> 
> v1 -> v2:
> 
> * allow also for odd "HTTP1/1 200 \r\n", i.e. SP after status-code but no reason-phrase
> * add some tests

s/HTTP1\/1/HTTP\/1.1/g; # even

**Comment by aldot** [comment]
ping?

**Comment by davewood** [comment]
ping2
