### ISSUE TITLE
EPIPE & ECONNRESET should not be fatal when writing out the request body if the server has already written out a response.

### ISSUE THREAD

**Issue by FGasper** [chansen/p5-http-tiny#121]
While looking at #120 I noticed that this:
```
        elsif ($! == EPIPE) {
            die(qq/Socket closed by remote server: $!\n/);
        }
```
… means that if the server receives the headers and rejects the request without accepting all of the headers, the EPIPE that HTTP::Tiny receives results in a failed request.

It seems more preferable in this case for HTTP::Tiny to check to see if the server has sent a 4xx or 5xx response, and if so, to report that failure rather than EPIPE.

**Comment by FGasper** [comment]
This is actually almost the same issue as #120; the smokes of that branch appear to fail because of ECONNRESET, which happens in the middle of the client’s write() system call.

**Comment by FGasper** [comment]
Having done a bit more investigation into why this was happening in the first place, I think this is _mostly_ a non-issue. The ECONNRESET was because the server was closing the TCP connection before having emptied its receive buffer, which caused an RST to be sent, which resulted in the ECONNRESET.

I do still think it would be better to handle EPIPE and ECONNRESET via a warning in the case where a response is already received, though.

**Comment by xdg** [comment]
While this might be a nice feature, the HTTP/1.1 spec doesn't require clients to process responses after a server connection terminates unexpectedly.  Doing this would significantly complicate the error handling code paths of HTTP::Tiny, so I'm closing this as a "Won't Fix".
