### ISSUE TITLE
timeout() method is not documented

### ISSUE THREAD

**Issue by FGasper** [chansen/p5-http-tiny#126]
Is this method meant for public consumption? I have a use for it and would like to call into it, but not if it’s potentially going to disappear in the future. :-P

Thank you!

**Comment by greg-kennedy** [comment]
I have the same question about `sub agent`.  It looks like these can be used to set a new value, or simply return the existing (if called with no args).

**Comment by digglife** [comment]
I suppose we can call it with confidence because actually every attribute has a predefined getter/setter method associated to it. 

```perl
    for my $accessor ( @attributes ) {
        *{$accessor} = sub {
            @_ > 1
                ? do {
                    delete $_[0]->{handle} if !$persist_ok{$accessor} && $_[1] ne $_[0]->{$accessor};
                    $_[0]->{$accessor} = $_[1]
                }
                : $_[0]->{$accessor};
        };
    }
```


`timeout` was explicitly defined just because it can be set without closing the existing connection. Refer to the commit 571119c and issue #82 when it's introduced.

```perl
sub timeout {
    my ($self, $timeout) = @_;
    if ( @_ > 1 ) {
        $self->{timeout} = $timeout;
        if ($self->{handle}) {
            $self->{handle}->timeout($timeout);
        }
    }
    return $self->{timeout};
}
```
