### ISSUE TITLE
setting a custom agent string isn't sent with content

### ISSUE THREAD

**Issue by japharl** [chansen/p5-http-tiny#129]
In window 1:
``
touch index ; while true; do cat index | nc -l 8888; done
``
In window 2:
``
vi test.pl
``
then
``
use HTTP::Tiny;
my $T = HTTP::Tiny->new({agent=>'asdf'});
$T->get("http://localhost:8888");
``
and
``
<esc>:wq!
``
Finally:
``
perl test.pl
``
Then, look at window 1.  While the agent was set to **asdf**, the agent retained original value.  Found in HTTP-tiny/0.076

**Comment by japharl** [comment]
Related to #126 .  Using:
``$T->agent("asdf");``
works.  The documentation should therefore be updated to reflect correct usage.

**Comment by karenetheridge** [comment]
Please try `HTTP::Tiny->new(agent=>'asdf');` -- the constructor takes a hash, not a hashref.

**Comment by karenetheridge** [comment]
You would have found this issue yourself if you'd used `use strict; use warnings;` in your code -- you would get an error like `Reference found where even-sized list expected at .../HTTP/Tiny.pm line 109.`
