### ISSUE TITLE
Options to force IPv4 or IPv6

### ISSUE THREAD

**Issue by rhansen** [chansen/p5-http-tiny#135]
IO::Socket::IP has a `Family` option that can be set to `AF_INET` or `AF_INET6` to force A or AAAA lookups, and a `Domain` option that can be set to `PF_INET` or `PF_INET6` to force the IP protocol. Please expose these options through the HTTP::Tiny constructor so that applications can force IPv4 or IPv6 connections.

**Comment by tomhukins** [comment]
Modules in the "Tiny" namespace should provide simple code that works for common use cases.  Generally, it doesn't matter whether an HTTP request uses IPv4 or IPv6.  I would encourage anyone interested in such customisation to use a more fully featured HTTP implementation instead.

**Comment by xdg** [comment]
I agree with Tom that this is outside the scope of HTTP::Tiny.  Closing.
