### ISSUE TITLE
ppc64le build is continuously failing on Travis-ci

### ISSUE THREAD

**Issue by sanjaymsh** [chansen/p5-http-tiny#138]
Hi,

I am enabling ppc64le's build on travis-ci so added the arch "ppc64le" in .travis.yml , but it's always failing for ppc64le. I have copy/pasted the error part of the log below (full log can be tracked on : https://travis-ci.com/github/sanjaymsh/p5-http-tiny/builds/181758901). Please have a look on this.
"............................................................
..............................................................
$ cpanm --version
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated"

I tried to increase the wait-time through "travis_wait". but doesn't help.

Thanks!!

**Comment by karenetheridge** [comment]
This doesn't look related to HTTP::Tiny at all -- `cpanm` is pre-installed
by travis itself, and it is hanging, so it appears that it (or more likely,
perl itself) was not built correctly? I'm not sure how we can dig into this
without more access to the build machine itself.

**Comment by sanjay-cpu** [comment]
Thanks @karenetheridge. I will discuss to travis community about this or try to find if there is any work around.

**Comment by Siddhesh-Ghadi** [comment]
Hi @sanjaymsh , the `cpanm` issue has been resolved on travis.

**Comment by sanjaymsh** [comment]
Thanks @Siddhesh-Ghadi.
