### ISSUE TITLE
Future of HTTP::Tiny

### ISSUE THREAD

**Issue by chansen** [chansen/p5-http-tiny#28]
We should have a clear plan for the future of HTTP::Tiny. HTTP::Tiny was designed as a proper alternative HTTP::Lite to bootstrap CPAN clients. In it's current state it's not a viable alternative to LWP. We don't support persistent connections, or support authentication besides basic access. Neither do we support proxy authentication.

It should be clear in the documentation that most users would benefit from a UA that support persistent connections, http/proxy auth.

I'm not against implementing a more efficient implementation of LWP, but HTTP::Tiny should be considered feature complete.

**Comment by Markvy** [comment]
Are there any plans these days to integrate HTTP::Tiny::Multipart?

**Comment by xdg** [comment]
No, we have no plans to do so.

**Comment by Markvy** [comment]
Okay then
