### ISSUE TITLE
Header field values must not allow CRLF

### ISSUE THREAD

**Issue by dagolden** [chansen/p5-http-tiny#48]
Header folding is now prohibited by the update spec: http://tools.ietf.org/html/rfc7230#section-3.2

We should make sure that CRLF is not included in header field values or replace it with a space, if so.

**Comment by chansen** [comment]
We use to validate header-field values, the behavior was changed <[01ebfa2cbc155b1aaba83a12473b2fbc144ca278](https://github.com/chansen/p5-http-tiny/commit/01ebfa2cbc155b1aaba83a12473b2fbc144ca278)> and later removed in < [878d4e6ac038d34f36d76a151a3ec0dcf1956f51](https://github.com/chansen/p5-http-tiny/commit/878d4e6ac038d34f36d76a151a3ec0dcf1956f51)>. I suggest we restore the original validation/assertion.
