### ISSUE TITLE
Clarify details of timeout in documentation

### ISSUE THREAD

**Issue by y** [chansen/p5-http-tiny#63]
The documentation doesn't give any details on the timeout- is it only for the connect or does it include inactivity. If the former, it should be noted as well as a suggestion to use eval/alarm to simulate an inactive timeout.

**Comment by chansen** [comment]
The timeout option specifies the maximum amount of time to to wait for a system call. The timeout is restarted upon a successful system call. If there is a need for a timeout for the request and response phase it could be trivially added.

**Comment by dagolden** [comment]
At work, we differentiate the connect timeout from the socket timeout, as people may have different tolerances for waiting for a server that isn't there versus waiting for an answer from one that is there.

I'm not opposed to adding that distinction.  It's a limited, targeted change.

**Comment by chansen** [comment]
We could implement a separate timeout for the "connection phase" (socket(2), bind(2) and connect(2)) and keep the current "inactivity timeout".

**Comment by y** [comment]
A user would still need to use eval/alarm to deal with [tarpits](https://en.wikipedia.org/wiki/Tarpit_%28networking%29) right? I frequently run into them, mostly of the unintentional sort (network/server misconfiguration).

**Comment by dagolden** [comment]
If the server is responding but just slowly, you'd need some sort of eval/alarm.  If you wanted to explore that, you could look at adding it to [HTTP::Tiny::UA](http://github.com/dagolden/HTTP-Tiny-UA)
