### ISSUE TITLE
110_mirror.t failures due to some kind of datetime issue

### ISSUE THREAD

**Issue by nanis** [chansen/p5-http-tiny#71]
I haven't investigated this yet, and it might be just due to something wrong with my setup, or Windows, or Visual C builds, but, for later reference, here are the failures:

<pre>#   Failed test 'mirror-01.txt request'             
#   at t\110_mirror.t line 70.                      
#          got: 'GET /modified.txt HTTP/1.1         
# Connection: close                                 
# Host: example.com                                 
# If-Modified-Since: Mon, 31 Jan 1994 23:00:00 GMT  
# User-Agent: HTTP-Tiny/0.056                       
# '                                                 
#     expected: 'GET /modified.txt HTTP/1.1         
# Connection: close                                 
# Host: example.com                                 
# If-Modified-Since: Tue, 01 Feb 1994 00:00:00 GMT  
# User-Agent: HTTP-Tiny/0.056                       
# '                                                 
                                                    
#   Failed test 'mirror-02.txt request'             
#   at t\110_mirror.t line 70.                      
#          got: 'GET /not-modified.txt HTTP/1.1     
# Connection: close                                 
# Host: example.com                                 
# If-Modified-Since: Mon, 31 Jan 1994 23:00:00 GMT  
# User-Agent: HTTP-Tiny/0.056                       
# '                                                 
#     expected: 'GET /not-modified.txt HTTP/1.1     
# Connection: close                                 
# Host: example.com                                 
# If-Modified-Since: Tue, 01 Feb 1994 00:00:00 GMT  
# User-Agent: HTTP-Tiny/0.056                       
# '                                                 
                                                    
#   Failed test 'mirror-02.txt file not overwritten'
#   at t\110_mirror.t line 82.                      
#          got: '760057200'                         
#     expected: '760060800'                         
# Looks like you failed 3 tests of 20.              </pre>

It looks like my `perl` thinks `Tue, 01 Feb 1994 00:00:00 GMT` is `Mon, 31 Jan 1994 23:00:00 GMT`.

**Comment by nanis** [comment]
I believe this is related to [Time zone insanity on Windows](http://www.nu42.com/2015/03/time-zone-insanity-on-windows.html) and [It all boils down to stat vs fstat from MSVCRT on Windows](http://www.nu42.com/2015/03/stat-vs-fstat-msvcrt-windows.html).

[Mojolicious fixed a similar problem](https://github.com/kraih/mojo/issues/761) by using the same method to deduce file modification times for both the reference and test resources.

With `HTTP::Tiny`s test set up, I am not sure how to fix the test, other than to declare the test a success if the received time is exactly an hour behind or some such contortion when daylight savings is in effect.

For the last failed test, one could fix the test by reading back the timestamp `stat` reports after `utime`:

    # maybe create a file
      (my $url_basename = $url) =~ s{.*/}{};
      if ( my $mtime = $timestamp{$url_basename} ) {
        open my $fh, ">", $tempfile;
        close $fh;
        utime $mtime, $mtime, $tempfile;
        $timestamp{$url_basename} = (stat $tempfile)[9];
      }

**Comment by chansen** [comment]
As a short time fix, this seems reasonable. In a longer term this is something the Perl core should emulate/correct considering all other emulations which Perl implements on Windows platform to emulate unix.

**Comment by chansen** [comment]
@nanis, Have you filed a bug at p5p with your findings?
