### ISSUE TITLE
record response time using HTTP::Tiny

### ISSUE THREAD

**Issue by sparvu** [chansen/p5-http-tiny#74]
Im planning writing a new HTTP client which should go over a number of HTTP/HTTPS requests, support  cookies and record the response times of each request. The recorder should be as small as possible in size, fast and be able to report the response time breakdown: time to connect, time to do the DNS something for example libcurl does.

Some questions: can I use HTTP::Tiny and get such statistics from the module itself ? Or can I use it together with WWW::Curl or some other Curl Perl consumer ?

Any hints ?

**Comment by dagolden** [comment]
That's not something that HTTP::Tiny supports.  Sorry.
