### ISSUE TITLE
Allow output to filehandle?

### ISSUE THREAD

**Issue by FGasper** [chansen/p5-http-tiny#76]
How odd would it be to add the ability to HTTP::Tiny to output to a filehandle rather than to an in-memory buffer?

**Comment by chansen** [comment]
This is already supported in HTTP::Tiny by using the `data_callback` option. It's documented in [->request](https://metacpan.org/pod/HTTP::Tiny#request).

```perl
$fh   = \*STDOUT;
%args = ( data_callback => sub { print {$fh} $_[0] } );
$res  = HTTP::Tiny->new->get('http://example.com', \%args);
```

**Comment by FGasper** [comment]
Ah, sorry to have missed that. Thank you, @chansen!
