### ISSUE TITLE
Allow manual setting of “Host” header?

### ISSUE THREAD

**Issue by FGasper** [chansen/p5-http-tiny#78]
For debugging purposes it would be very handy to be able to set the “Host” header, e.g.:
```
perl -MYAML::Syck -MHTTP::Tiny-e'my $h = HTTP::Tiny->new(); print Dump( $h->get( "http://localhost/D37ACEE71582AF2D80F9AECCC2531149.txt", { headers => { Host => "abcde.com" } } ) )'
```

I get why this is actively blocked in the module, but should it not be assumed that a caller that sets “Host” has a good reason to do so?

**Comment by xdg** [comment]
The spec requires the `Host` field to match the authority, so this isn't something we allow.

**Comment by FGasper** [comment]
@xdg I understand that; however, setting a Host header is useful for debugging.

**Comment by xdg** [comment]
Could you explain your use case more fully?  Note there is now a `peer` option (in the 0.057-TRIAL) that can let you send a request to an arbitrary IP; that keeps the URI and Host in sync while allowing the request to go to, say, localhost.  Does that achieve what you need?

**Comment by FGasper** [comment]
@xdg Yes, I think `peer`

**Comment by FGasper** [comment]
… will do the trick. :) 👍

**Comment by xdg** [comment]
Great!
