### ISSUE TITLE
Set content length to 0 for PUT and POST

### ISSUE THREAD

**Issue by xdg** [chansen/p5-http-tiny#86]
Apparently, IIS issues 411 for a POST with no content-length.

We stopped writing-content length of zero for the empty string because that
caused problems for GET, etc. with no semantics for a content body.

So we should do it for PUT/POST but not for other methods.

**Comment by vti** [comment]
There is also a related issue for Azure, they want Content-Length: 0 for PUT, why _with_ content, instead they require x-ms-content-length header. I tried to overwrite Content-Length passing it as headers options, but this code recalculates it:

```
$request->{headers}{'content-length'} = length $content
              unless $request->{headers}{'content-length'}
                  || $request->{headers}{'transfer-encoding'};
```
