### ISSUE TITLE
“redirects” is lost if an internal exception happens

### ISSUE THREAD

**Issue by FGasper** [chansen/p5-http-tiny#97]
Where request() returns status 599, it needs to add:

```
@{$args->{_redirects}} ? ('redirects'=>delete $args->{_redirects}) : ()
```

**Comment by xdg** [comment]
Shipped as HTTP-Tiny-0.067-TRIAL.  If you can replicate, please try that and confirm that it works.

**Comment by FGasper** [comment]
Confirmed: This resolves the issue. Thank you!

**Comment by FGasper** [comment]
@xdg

**Comment by xdg** [comment]
Excellent!  Thanks for testing it out.  I'm going to let 0.067-TRIAL smoke for a few days and then will ship the stable release.

**Comment by FGasper** [comment]
@xdg Has this had long enough to incubate, do you think? We’d like to bundle the new version, but our infrastructure presumes we’re grabbing a production release.

**Comment by xdg** [comment]
Yes.  Thanks for the reminder.  0.068 shipped to CPAN just now.
